'use client';

import { useState } from 'react';

interface Config {
  redirectWww: 'none' | 'www' | 'nowww';
  forceHttps: boolean;
  customDomain: string;
  errorPages: { code: string; path: string }[];
  expires: boolean;
  gzip: boolean;
  hotlinkProtection: boolean;
  allowedDomain: string;
  directoryListing: boolean;
  phpMaxUpload: string;
  customRedirects: { from: string; to: string; type: '301' | '302' }[];
  corsEnabled: boolean;
  corsDomain: string;
  xssProtection: boolean;
  clickjacking: boolean;
}

const DEFAULT: Config = {
  redirectWww: 'none',
  forceHttps: true,
  customDomain: 'example.com',
  errorPages: [
    { code: '404', path: '/404.html' },
    { code: '500', path: '/500.html' },
  ],
  expires: true,
  gzip: true,
  hotlinkProtection: false,
  allowedDomain: 'example.com',
  directoryListing: true,
  phpMaxUpload: '64',
  customRedirects: [],
  corsEnabled: false,
  corsDomain: '*',
  xssProtection: true,
  clickjacking: true,
};

function buildHtaccess(c: Config): string {
  const lines: string[] = [];

  const push = (...l: string[]) => lines.push(...l);
  const section = (title: string) => push('', `# ${title}`, '# ' + '-'.repeat(title.length));

  push('# Generated by Pixvert .htaccess Generator', '# https://pixvert-one.vercel.app/tools/htaccess-generator', '');

  // Force HTTPS
  if (c.forceHttps) {
    section('Force HTTPS');
    push(
      '<IfModule mod_rewrite.c>',
      '  RewriteEngine On',
      '  RewriteCond %{HTTPS} off',
      '  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]',
      '</IfModule>',
    );
  }

  // WWW redirect
  if (c.redirectWww !== 'none' && c.customDomain) {
    section('WWW redirect');
    const domain = c.customDomain.replace(/^www\./, '');
    if (c.redirectWww === 'www') {
      push(
        '<IfModule mod_rewrite.c>',
        '  RewriteEngine On',
        `  RewriteCond %{HTTP_HOST} !^www\\. [NC]`,
        `  RewriteRule ^ https://www.${domain}%{REQUEST_URI} [L,R=301]`,
        '</IfModule>',
      );
    } else {
      push(
        '<IfModule mod_rewrite.c>',
        '  RewriteEngine On',
        `  RewriteCond %{HTTP_HOST} ^www\\.${domain.replace('.', '\\.')} [NC]`,
        `  RewriteRule ^ https://${domain}%{REQUEST_URI} [L,R=301]`,
        '</IfModule>',
      );
    }
  }

  // Directory listing
  section('Directory listing');
  push(c.directoryListing ? 'Options -Indexes' : 'Options +Indexes');

  // Error pages
  const activeErrors = c.errorPages.filter((e) => e.code && e.path);
  if (activeErrors.length > 0) {
    section('Custom error pages');
    activeErrors.forEach((e) => push(`ErrorDocument ${e.code} ${e.path}`));
  }

  // Hotlink protection
  if (c.hotlinkProtection && c.allowedDomain) {
    section('Hotlink protection');
    push(
      '<IfModule mod_rewrite.c>',
      '  RewriteEngine On',
      `  RewriteCond %{HTTP_REFERER} !^$`,
      `  RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${c.allowedDomain.replace('.', '\\.')} [NC]`,
      '  RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC]',
      '</IfModule>',
    );
  }

  // Gzip compression
  if (c.gzip) {
    section('Enable Gzip compression');
    push(
      '<IfModule mod_deflate.c>',
      '  AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css',
      '  AddOutputFilterByType DEFLATE application/xml application/xhtml+xml application/rss+xml',
      '  AddOutputFilterByType DEFLATE application/javascript application/x-javascript',
      '  AddOutputFilterByType DEFLATE application/json application/ld+json',
      '</IfModule>',
    );
  }

  // Browser caching / Expires
  if (c.expires) {
    section('Browser caching (Expires)');
    push(
      '<IfModule mod_expires.c>',
      '  ExpiresActive On',
      '  ExpiresByType image/jpg "access plus 1 year"',
      '  ExpiresByType image/jpeg "access plus 1 year"',
      '  ExpiresByType image/gif "access plus 1 year"',
      '  ExpiresByType image/png "access plus 1 year"',
      '  ExpiresByType image/webp "access plus 1 year"',
      '  ExpiresByType image/svg+xml "access plus 1 year"',
      '  ExpiresByType text/css "access plus 1 month"',
      '  ExpiresByType application/javascript "access plus 1 month"',
      '  ExpiresByType text/html "access plus 1 day"',
      '</IfModule>',
    );
  }

  // Security headers
  const secHeaders: string[] = [];
  if (c.xssProtection) secHeaders.push('  Header set X-XSS-Protection "1; mode=block"');
  if (c.clickjacking) secHeaders.push('  Header always append X-Frame-Options SAMEORIGIN');
  if (secHeaders.length > 0) {
    section('Security headers');
    push('<IfModule mod_headers.c>', ...secHeaders, '</IfModule>');
  }

  // CORS
  if (c.corsEnabled) {
    section('CORS headers');
    push(
      '<IfModule mod_headers.c>',
      `  Header set Access-Control-Allow-Origin "${c.corsDomain}"`,
      '  Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"',
      '  Header set Access-Control-Allow-Headers "Content-Type"',
      '</IfModule>',
    );
  }

  // PHP upload limit
  if (c.phpMaxUpload && parseInt(c.phpMaxUpload) > 0) {
    section('PHP settings');
    push(
      '<IfModule mod_php.c>',
      `  php_value upload_max_filesize ${c.phpMaxUpload}M`,
      `  php_value post_max_size ${c.phpMaxUpload}M`,
      '</IfModule>',
    );
  }

  // Custom redirects
  const activeRedirects = c.customRedirects.filter((r) => r.from && r.to);
  if (activeRedirects.length > 0) {
    section('Custom redirects');
    activeRedirects.forEach((r) => push(`Redirect ${r.type} ${r.from} ${r.to}`));
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

function Toggle({ label, checked, onChange, hint }: { label: string; checked: boolean; onChange: (v: boolean) => void; hint?: string }) {
  return (
    <label className="flex items-center gap-3 cursor-pointer">
      <button
        role="switch"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        className={`relative inline-flex h-5 w-9 shrink-0 rounded-full transition-colors ${checked ? 'bg-indigo-600' : 'bg-slate-300 dark:bg-slate-600'}`}
      >
        <span className={`inline-block h-4 w-4 rounded-full bg-white shadow transform transition-transform mt-0.5 ${checked ? 'translate-x-4' : 'translate-x-0.5'}`} />
      </button>
      <span className="text-sm text-slate-700 dark:text-slate-300">
        {label}
        {hint && <span className="ml-1 text-xs text-slate-400">{hint}</span>}
      </span>
    </label>
  );
}

export default function HtaccessGeneratorTool() {
  const [c, setC] = useState<Config>(DEFAULT);
  const [copied, setCopied] = useState(false);

  const set = <K extends keyof Config>(key: K, val: Config[K]) => setC((prev) => ({ ...prev, [key]: val }));

  const output = buildHtaccess(c);

  const copy = async () => {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const addRedirect = () => set('customRedirects', [...c.customRedirects, { from: '', to: '', type: '301' }]);
  const updateRedirect = (i: number, field: keyof Config['customRedirects'][0], val: string) => {
    const updated = c.customRedirects.map((r, idx) => idx === i ? { ...r, [field]: val } : r);
    set('customRedirects', updated);
  };
  const removeRedirect = (i: number) => set('customRedirects', c.customRedirects.filter((_, idx) => idx !== i));

  const updateErrorPage = (i: number, field: 'code' | 'path', val: string) => {
    const updated = c.errorPages.map((e, idx) => idx === i ? { ...e, [field]: val } : e);
    set('errorPages', updated);
  };

  return (
    <div className="max-w-5xl mx-auto w-full px-4 py-10">
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-3">.htaccess Generator — Free</h1>
        <p className="text-slate-500 dark:text-slate-400 max-w-xl mx-auto">
          Build an Apache .htaccess file with HTTPS redirects, caching, security headers, custom errors, and more. No signup required.
        </p>
      </div>

      <div className="grid sm:grid-cols-2 gap-6">
        {/* Options */}
        <div className="space-y-6">

          {/* Domain & HTTPS */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Domain & HTTPS</p>
            <div>
              <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">Domain (without www)</label>
              <input type="text" value={c.customDomain} onChange={(e) => set('customDomain', e.target.value)}
                placeholder="example.com"
                className="w-full rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
            <Toggle label="Force HTTPS" checked={c.forceHttps} onChange={(v) => set('forceHttps', v)} />
            <div>
              <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">WWW redirect</label>
              <select value={c.redirectWww} onChange={(e) => set('redirectWww', e.target.value as Config['redirectWww'])}
                className="w-full rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500">
                <option value="none">No redirect</option>
                <option value="www">Redirect to www</option>
                <option value="nowww">Redirect to non-www</option>
              </select>
            </div>
          </div>

          {/* Performance */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Performance</p>
            <Toggle label="Enable Gzip compression" checked={c.gzip} onChange={(v) => set('gzip', v)} />
            <Toggle label="Browser caching (Expires headers)" checked={c.expires} onChange={(v) => set('expires', v)} />
          </div>

          {/* Security */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Security</p>
            <Toggle label="Disable directory listing" checked={c.directoryListing} onChange={(v) => set('directoryListing', v)} />
            <Toggle label="X-XSS-Protection header" checked={c.xssProtection} onChange={(v) => set('xssProtection', v)} />
            <Toggle label="X-Frame-Options (clickjacking)" checked={c.clickjacking} onChange={(v) => set('clickjacking', v)} />
            <div className="space-y-2">
              <Toggle label="Hotlink protection" checked={c.hotlinkProtection} onChange={(v) => set('hotlinkProtection', v)} />
              {c.hotlinkProtection && (
                <input type="text" value={c.allowedDomain} onChange={(e) => set('allowedDomain', e.target.value)}
                  placeholder="example.com"
                  className="w-full rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
              )}
            </div>
            <div className="space-y-2">
              <Toggle label="CORS headers" checked={c.corsEnabled} onChange={(v) => set('corsEnabled', v)} />
              {c.corsEnabled && (
                <input type="text" value={c.corsDomain} onChange={(e) => set('corsDomain', e.target.value)}
                  placeholder="* or https://example.com"
                  className="w-full rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
              )}
            </div>
          </div>

          {/* PHP */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">PHP</p>
            <div>
              <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">Max upload size (MB, 0 to disable)</label>
              <input type="number" min="0" max="2048" value={c.phpMaxUpload} onChange={(e) => set('phpMaxUpload', e.target.value)}
                className="w-full rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
          </div>

          {/* Error pages */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Custom error pages</p>
            {c.errorPages.map((e, i) => (
              <div key={i} className="flex gap-2">
                <input type="text" value={e.code} onChange={(ev) => updateErrorPage(i, 'code', ev.target.value)}
                  placeholder="404" className="w-20 rounded-lg border border-slate-300 dark:border-slate-600 px-2 py-1.5 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
                <input type="text" value={e.path} onChange={(ev) => updateErrorPage(i, 'path', ev.target.value)}
                  placeholder="/error.html" className="flex-1 rounded-lg border border-slate-300 dark:border-slate-600 px-2 py-1.5 text-sm text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
              </div>
            ))}
          </div>

          {/* Custom redirects */}
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-4 space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wide">Custom redirects</p>
              <button onClick={addRedirect} className="text-xs font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-800">+ Add</button>
            </div>
            {c.customRedirects.map((r, i) => (
              <div key={i} className="flex gap-2 items-center">
                <select value={r.type} onChange={(e) => updateRedirect(i, 'type', e.target.value)}
                  className="w-16 rounded-lg border border-slate-300 dark:border-slate-600 px-1 py-1.5 text-xs bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500">
                  <option>301</option>
                  <option>302</option>
                </select>
                <input type="text" value={r.from} onChange={(e) => updateRedirect(i, 'from', e.target.value)}
                  placeholder="/old-page" className="flex-1 rounded-lg border border-slate-300 dark:border-slate-600 px-2 py-1.5 text-xs text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
                <input type="text" value={r.to} onChange={(e) => updateRedirect(i, 'to', e.target.value)}
                  placeholder="https://example.com/new" className="flex-1 rounded-lg border border-slate-300 dark:border-slate-600 px-2 py-1.5 text-xs text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500" />
                <button onClick={() => removeRedirect(i)} className="text-slate-400 hover:text-red-500 text-xs">✕</button>
              </div>
            ))}
            {c.customRedirects.length === 0 && (
              <p className="text-xs text-slate-400">No custom redirects. Click + Add to add one.</p>
            )}
          </div>
        </div>

        {/* Output */}
        <div className="space-y-3">
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden sticky top-4">
            <div className="flex items-center justify-between px-4 py-2 bg-slate-50 dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700">
              <span className="text-xs font-semibold text-slate-600 dark:text-slate-400">.htaccess</span>
              <button onClick={copy} className="text-xs font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-800 transition-colors">
                {copied ? '✓ Copied!' : 'Copy all'}
              </button>
            </div>
            <pre className="px-4 py-3 text-xs font-mono text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-900 overflow-x-auto whitespace-pre max-h-[70vh] overflow-y-auto">
              {output}
            </pre>
          </div>
        </div>
      </div>

      <section className="mt-12 grid sm:grid-cols-3 gap-6 text-sm">
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
          <div className="text-2xl mb-2">⚡</div>
          <h2 className="font-semibold text-slate-800 dark:text-slate-200 mb-1">Performance rules</h2>
          <p className="text-slate-500 dark:text-slate-400">Gzip compression and browser caching headers speed up page loads automatically.</p>
        </div>
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
          <div className="text-2xl mb-2">🔒</div>
          <h2 className="font-semibold text-slate-800 dark:text-slate-200 mb-1">Security headers</h2>
          <p className="text-slate-500 dark:text-slate-400">XSS protection, clickjacking prevention, hotlink blocking and CORS settings in one click.</p>
        </div>
        <div className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
          <div className="text-2xl mb-2">↪️</div>
          <h2 className="font-semibold text-slate-800 dark:text-slate-200 mb-1">Redirects & rewrites</h2>
          <p className="text-slate-500 dark:text-slate-400">301/302 custom redirects, HTTPS enforcement, and www/non-www canonicalization.</p>
        </div>
      </section>
    </div>
  );
}
